#define ID                              1
#define BOOL_TRUE                       2
#define BOOL_FALSE                      3
#define DEPTH_WRITE_MASK_ALL            4
#define DEPTH_WRITE_MASK_ZERO           5
#define DEPTH_ENABLE                    6
#define ASSIGN                          7
#define SEMI_COLON                      8
#define DEPTH_WRITE_MASK                9
#define DEPTH_STENCIL_STATE            10
#define L_BRACKET                      11
#define R_BRACKET                      12
