-- direct x lua functions and enumerations

dx = {}
-- enum D3D11_FILTER
dx.D3D11_FILTER_MIN_MAG_MIP_POINT	= 0
dx.D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR = 0x1
dx.D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT	= 0x4
dx.D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR	= 0x5
dx.D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT	= 0x10
dx.D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR	= 0x11
dx.D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT	= 0x14
dx.D3D11_FILTER_MIN_MAG_MIP_LINEAR	= 0x15
dx.D3D11_FILTER_ANISOTROPIC	= 0x55
dx.D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT	= 0x80
dx.D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR	= 0x81
dx.D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT	= 0x84
dx.D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR	= 0x85
dx.D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT	= 0x90
dx.D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR	= 0x91
dx.D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT	= 0x94
dx.D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR	= 0x95
dx.D3D11_FILTER_COMPARISON_ANISOTROPIC	= 0xd5

-- enum D3D11_TEXTURE_ADDRESS_MODE
dx.D3D11_TEXTURE_ADDRESS_WRAP	= 1
dx.D3D11_TEXTURE_ADDRESS_MIRROR = 2
dx.D3D11_TEXTURE_ADDRESS_CLAMP	= 3
dx.D3D11_TEXTURE_ADDRESS_BORDER = 4
dx.D3D11_TEXTURE_ADDRESS_MIRROR_ONCE = 5

-- enum D3D11_COMPARISON_FUNC
dx.D3D11_COMPARISON_NEVER	= 1
dx.D3D11_COMPARISON_LESS	= 2
dx.D3D11_COMPARISON_EQUAL	= 3
dx.D3D11_COMPARISON_LESS_EQUAL	= 4
dx.D3D11_COMPARISON_GREATER	= 5
dx.D3D11_COMPARISON_NOT_EQUAL	= 6
dx.D3D11_COMPARISON_GREATER_EQUAL	= 7
dx.D3D11_COMPARISON_ALWAYS	= 8

-- enum D3D11_DEPTH_WRITE_MASK
dx.D3D11_DEPTH_WRITE_MASK_ZERO	= 0
dx.D3D11_DEPTH_WRITE_MASK_ALL	= 1

-- enum D3D11_COMPARISON_FUNC
dx.D3D11_COMPARISON_NEVER	= 1
dx.D3D11_COMPARISON_LESS	= 2
dx.D3D11_COMPARISON_EQUAL	= 3
dx.D3D11_COMPARISON_LESS_EQUAL	= 4
dx.D3D11_COMPARISON_GREATER	= 5
dx.D3D11_COMPARISON_NOT_EQUAL	= 6
dx.D3D11_COMPARISON_GREATER_EQUAL	= 7
dx.D3D11_COMPARISON_ALWAYS	= 8

dx.D3D11_DEFAULT_STENCIL_READ_MASK = 0xff
dx.D3D11_DEFAULT_STENCIL_WRITE_MASK	= 0xff

-- enum D3D11_STENCIL_OP
dx.D3D11_STENCIL_OP_KEEP	= 1
dx.D3D11_STENCIL_OP_ZERO	= 2
dx.D3D11_STENCIL_OP_REPLACE	= 3
dx.D3D11_STENCIL_OP_INCR_SAT	= 4
dx.D3D11_STENCIL_OP_DECR_SAT	= 5
dx.D3D11_STENCIL_OP_INVERT	= 6
dx.D3D11_STENCIL_OP_INCR	= 7
dx.D3D11_STENCIL_OP_DECR	= 8


--	enum D3D11_BLEND
dx.D3D11_BLEND_ZERO	= 1
dx.D3D11_BLEND_ONE	= 2
dx.D3D11_BLEND_SRC_COLOR	= 3
dx.D3D11_BLEND_INV_SRC_COLOR	= 4
dx.D3D11_BLEND_SRC_ALPHA	= 5
dx.D3D11_BLEND_INV_SRC_ALPHA	= 6
dx.D3D11_BLEND_DEST_ALPHA	= 7
dx.D3D11_BLEND_INV_DEST_ALPHA	= 8
dx.D3D11_BLEND_DEST_COLOR	= 9
dx.D3D11_BLEND_INV_DEST_COLOR	= 10
dx.D3D11_BLEND_SRC_ALPHA_SAT	= 11
dx.D3D11_BLEND_BLEND_FACTOR	= 14
dx.D3D11_BLEND_INV_BLEND_FACTOR	= 15
dx.D3D11_BLEND_SRC1_COLOR	= 16
dx.D3D11_BLEND_INV_SRC1_COLOR	= 17
dx.D3D11_BLEND_SRC1_ALPHA	= 18
dx.D3D11_BLEND_INV_SRC1_ALPHA	= 19

-- enum D3D11_BLEND_OP
dx.D3D11_BLEND_OP_ADD	= 1
dx.D3D11_BLEND_OP_SUBTRACT	= 2
dx.D3D11_BLEND_OP_REV_SUBTRACT	= 3
dx.D3D11_BLEND_OP_MIN	= 4
dx.D3D11_BLEND_OP_MAX	= 5

-- enum D3D11_COLOR_WRITE_ENABLE
dx.D3D11_COLOR_WRITE_ENABLE_RED	= 1
dx.D3D11_COLOR_WRITE_ENABLE_GREEN	= 2
dx.D3D11_COLOR_WRITE_ENABLE_BLUE	= 4
dx.D3D11_COLOR_WRITE_ENABLE_ALPHA	= 8
dx.D3D11_COLOR_WRITE_ENABLE_ALL	=
	dx.D3D11_COLOR_WRITE_ENABLE_RED +
	dx.D3D11_COLOR_WRITE_ENABLE_GREEN +
	dx.D3D11_COLOR_WRITE_ENABLE_BLUE +
	dx.D3D11_COLOR_WRITE_ENABLE_ALPHA

-- enum D3D11_FILL_MODE
dx.D3D11_FILL_WIREFRAME	= 2
dx.D3D11_FILL_SOLID = 3

-- enum D3D11_CULL_MODE
dx.D3D11_CULL_NONE	= 1
dx.D3D11_CULL_FRONT	= 2
dx.D3D11_CULL_BACK	= 3


local FLT_MAX = 3.402823466e+38
local D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT = 8

-- create default blend state
local function default_blend_state()
	b = {}
	b["AlphaToCoverageEnable"] = 0
	b["IndependentBlendEnable"] = 0
	for i = 0, D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT - 1 do
		b[i] = {}
		b[i]["BlendEnable"] = 0
		b[i]["SrcBlend"] = dx.D3D11_BLEND_ONE
		b[i]["DestBlend"] = dx.D3D11_BLEND_ONE
		b[i]["BlendOp"] = dx.D3D11_BLEND_OP_ADD
		b[i]["SrcBlendAlpha"] = dx.D3D11_BLEND_ONE
		b[i]["DestBlendAlpha"] = dx.D3D11_BLEND_ONE
		b[i]["BlendOpAlpha"] = dx.D3D11_BLEND_OP_ADD
		b[i]["RenderTargetWriteMask"] = dx.D3D11_COLOR_WRITE_ENABLE_ALL
	end
	return b
end

-- create default depth stencil state
local function default_depth_stencil_state()
	d = {}
	d["DepthEnable"] = 0
	d["DepthWriteMask"] = dx.D3D11_DEPTH_WRITE_MASK_ALL
	d["DepthFunc"] = dx.D3D11_COMPARISON_LESS
	d["StencilEnable"] = 0
	d["StencilReadMask"] = dx.D3D11_DEFAULT_STENCIL_READ_MASK
	d["StencilWriteMask"] = dx.D3D11_DEFAULT_STENCIL_WRITE_MASK

	d["FrontStencilFailOp"] = dx.D3D11_STENCIL_OP_KEEP
	d["FrontStencilDepthFailOp"] = dx.D3D11_STENCIL_OP_KEEP
	d["FrontStencilPassOp"] = dx.D3D11_STENCIL_OP_KEEP
	d["FrontStencilFunc"] = dx.D3D11_COMPARISON_ALWAYS

	d["BackStencilFailOp"] = dx.D3D11_STENCIL_OP_KEEP
	d["BackStencilDepthFailOp"] = dx.D3D11_STENCIL_OP_KEEP
	d["BackStencilPassOp"] = dx.D3D11_STENCIL_OP_KEEP
	d["BackStencilFunc"] = dx.D3D11_COMPARISON_ALWAYS

	return d
end

-- create a default sampler
local function default_sampler_state()
	s = {}
	s["Filter"] = dx.D3D11_FILTER_MIN_MAG_MIP_POINT
	s["AddressU"] = dx.D3D11_TEXTURE_ADDRESS_CLAMP
	s["AddressV"] = dx.D3D11_TEXTURE_ADDRESS_CLAMP
	s["AddressW"] = dx.D3D11_TEXTURE_ADDRESS_CLAMP
    s["MipLODBias"] = 0
	s["MaxAnisotropy"] = 1
	s["ComparisonFunc"] = dx.D3D11_COMPARISON_NEVER
	s["BorderColor"] = { 1.0, 1.0, 1.0, 1.0 }
	s["MinLOD"] = -FLT_MAX
	s["MaxLOD"] = FLT_MAX
	return s
end

local function default_rasterizer_state()
	r = {}
	r["FillMode"] = dx.D3D11_FILL_SOLID
	r["CullMode"] = dx.D3D11_CULL_BACK
	r["FrontCounterClockwise"] = 0
	r["DepthBias"] = 0 -- D3D11_DEFAULT_DEPTH_BIAS_CLAMP
	r["DepthBiasClamp"] = 0 -- D3D11_DEFAULT_DEPTH_BIAS_CLAMP
	r["SlopeScaledDepthBias"] = 0 -- D3D11_DEFAULT_SLOPE_SCALED_DEPTH_BIAS
	r["DepthClipEnable"] = 1
	r["ScissorEnable"] = 0
	r["MultisampleEnable"] = 0
	r["AntialiasedLineEnable"] = 0
	return r
end



dx.sampler_state = default_sampler_state()
dx.blend_state = default_blend_state()
dx.depth_stencil_state = default_depth_stencil_state()
dx.rasterizer_state = default_rasterizer_state()

